### ISSUE TITLE
issue to add new badges 

### ISSUE THREAD

**Issue by gurjeetsinghvirdee** [Ileriayo/markdown-badges#150]
Whenever I try to add new badge in same format like written before but that time not adding , getting a badge but in the right side where we get link , link are not supposed to be print , it's a glitch or something else don't know , I tried 6th time and finally it's added .. Please check that if you get the same issue or not 
![Screenshot (585)](https://user-images.githubusercontent.com/73753957/127750879-a6475a2b-6723-4eb2-9f7d-597bafb52102.png)

**Comment by mehtaAnsh** [comment]
Hey @gurjeetsinghvirdee , I face the same issues sometimes. It's an issue with GitHub and browser caching the page. Since there are a lot of badges to be added, the browser gets overwhelmed and may fail to render the new badges (I've faced this twice). This gets resolved by a simple hard refresh. Let me know if this got resolved with a refresh.

**Comment by gurjeetsinghvirdee** [comment]
> Hey @gurjeetsinghvirdee , I face the same issues sometimes. It's an issue with GitHub and browser caching the page. Since there are a lot of badges to be added, the browser gets overwhelmed and may fail to render the new badges (I've faced this twice). This gets resolved by a simple hard refresh. Let me know if this got resolved with a refresh.

Issue resolved by refreshing the page thanks mate!
