### ISSUE TITLE
Badge Request - Asp.Net technologies

### ISSUE THREAD

**Issue by chirag4242** [Ileriayo/markdown-badges#539]
Please add a badge for Asp.Net MVC, Asp.Net WebAPI, EF Core, etc.

**Comment by Ari-Qu3sadillas** [comment]
Hello Chirag.
There isn't any ASP or EF logo on the official MS documentation. 

Also, remember that all the ASP variations (Classic, Webforms, Razor, MVC, API, Minimal API, etc.) are part of the same framework so you can't separate them.

Even that an "ASP API" badge is added it won't be added as the other ones, because the badges provider on this repository [Shields](https://shields.io/) get the brand icons from the [Simple Icons](https://simpleicons.org/)  project and if you want to add a new logo on that project you might follow a lot of design rules and obviously be an official logo.

I recommend you use the .Net badge and change the text with the technology of your preference or if you want to use a custom logo that is not on the Simple Icons project you can use images on base64 format

example:
```code
Change the @[...] with your logo data


[@Whatever](
https://img.shields.io/badge/[@TECHNAME]-[@HEX-COLOR]?style=for-the-badge&logo=data:image/png;base64,[@IMAGE-DATA]
)
```

Have a nice day 😊
<img src="https://stickershop.line-scdn.net/stickershop/v1/sticker/10950873/android/sticker.png">

**Comment by chirag4242** [comment]
Thanks, that's informative 👍. Yea, using the .Net logo, and changing the text would work. I just didn't want to use similar logos for different areas, that's why I thought if we made more badges for those technologies that would be great. But, you're right - it doesn't make sense to use other logos, as they don't exist and come from a similar .Net group.
